CREATE TABLE properties
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_name  VARCHAR(255),
    property_value VARCHAR(255),
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

ALTER TABLE product_properties
    ADD property_id BIGINT;

ALTER TABLE product_properties
    ADD CONSTRAINT FK_PRODUCT_PROPERTIES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

ALTER TABLE product_properties
    DROP COLUMN id;

ALTER TABLE product_properties
    DROP COLUMN property_name;

ALTER TABLE product_properties
    DROP COLUMN property_value;

ALTER TABLE product_properties
    ALTER COLUMN product_id SET NOT NULL;

ALTER TABLE product_properties
    ADD CONSTRAINT pk_product_properties PRIMARY KEY (product_id, property_id);