CREATE TABLE carts
(
    product_quantity INTEGER,
    user_id          BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (user_id, product_id)
);

CREATE TABLE order_details
(
    product_quantity INTEGER,
    subtotal         DOUBLE PRECISION,
    order_id         BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    CONSTRAINT pk_order_details PRIMARY KEY (order_id, product_id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    address_id   BIGINT,
    payment_id   BIGINT,
    shipment_fee DOUBLE PRECISION,
    order_status VARCHAR(255),
    total_price  DOUBLE PRECISION,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE payment_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name SMALLINT,
    CONSTRAINT pk_payment_categories PRIMARY KEY (id)
);

CREATE TABLE payments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id      BIGINT,
    payment_category_id BIGINT,
    payment_status      VARCHAR(255),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE product_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_product_categories PRIMARY KEY (id)
);

CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id    BIGINT                                  NOT NULL,
    product_name   VARCHAR(255)                            NOT NULL,
    price          DOUBLE PRECISION                        NOT NULL,
    cost_price     DOUBLE PRECISION                        NOT NULL,
    sku            VARCHAR(255)                            NOT NULL,
    added_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    stock_quantity INTEGER,
    description    VARCHAR(255),
    weight         DOUBLE PRECISION,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE transaction_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name SMALLINT,
    CONSTRAINT pk_transaction_categories PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_gateway_transaction_id VARCHAR(255),
    transaction_category_id        BIGINT,
    status                         VARCHAR(255),
    ammount                        DOUBLE PRECISION,
    created_at                     TIMESTAMP WITHOUT TIME ZONE,
    updated_at                     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE user_addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    province         VARCHAR(255),
    district         VARCHAR(255),
    ward             VARCHAR(255),
    specific_address VARCHAR(255),
    CONSTRAINT pk_user_addresses PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                         VARCHAR(255)                            NOT NULL,
    email                            VARCHAR(100)                            NOT NULL,
    password_hash                    VARCHAR(255),
    email_verified                   BOOLEAN                                 NOT NULL,
    activation_token                 VARCHAR(255)                            NOT NULL,
    activation_token_expiration_date TIMESTAMP WITHOUT TIME ZONE,
    reset_token                      VARCHAR(255)                            NOT NULL,
    reset_token_expiration_date      TIMESTAMP WITHOUT TIME ZONE,
    phone_number                     VARCHAR(10),
    image_url                        VARCHAR(255),
    user_role                        VARCHAR(255),
    is_deleted                       BOOLEAN                                 NOT NULL,
    created_at                       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_update                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_address UNIQUE (address_id);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_payment UNIQUE (payment_id);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_transaction UNIQUE (transaction_id);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_payment_gateway_transaction UNIQUE (payment_gateway_transaction_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES user_addresses (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payments (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDER_DETAILS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDER_DETAILS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_PAYMENT_CATEGORY FOREIGN KEY (payment_category_id) REFERENCES payment_categories (id);

ALTER TABLE payments
    ADD CONSTRAINT FK_PAYMENTS_ON_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES transactions (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES product_categories (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_TRANSACTIONCATEGORY FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories (id);

ALTER TABLE user_addresses
    ADD CONSTRAINT FK_USER_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);