CREATE TABLE batches
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id                BIGINT,
    po_id                     BIGINT,
    product_variant_id        BIGINT,
    unit                      VARCHAR(255),
    quantity                  DOUBLE PRECISION,
    mfg                       TIMESTAMP WITHOUT TIME ZONE,
    warranty_period_in_months INTEGER,
    warehouse                 VARCHAR(255),
    batch_date                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_batches PRIMARY KEY (id)
);

CREATE TABLE customer_carts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id        BIGINT                                  NOT NULL,
    product_variant_id BIGINT                                  NOT NULL,
    quantity           INTEGER,
    CONSTRAINT pk_customer_carts PRIMARY KEY (id)
);

CREATE TABLE customer_order_details
(
    customer_order_id  BIGINT,
    product_variant_id BIGINT,
    quantity           INTEGER,
    subtotal           DOUBLE PRECISION,
    order_id           BIGINT NOT NULL,
    product_id         BIGINT NOT NULL,
    CONSTRAINT pk_customer_order_details PRIMARY KEY (order_id, product_id)
);

CREATE TABLE customer_orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  BIGINT,
    address_id   BIGINT,
    shipment_fee DOUBLE PRECISION,
    order_status VARCHAR(255),
    total_price  DOUBLE PRECISION,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customer_orders PRIMARY KEY (id)
);

CREATE TABLE inventory_transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_type   VARCHAR(255),
    product_variant_id BIGINT,
    batch_id           BIGINT,
    customer_order_id  BIGINT,
    po_id              BIGINT,
    note               VARCHAR(255),
    quantity           DOUBLE PRECISION,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_transactions PRIMARY KEY (id)
);

CREATE TABLE payment_transactions
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_gateway_transaction_id VARCHAR(255),
    payment_transaction_type       VARCHAR(255),
    payment_method                 VARCHAR(255),
    status                         VARCHAR(255),
    product_id                     BIGINT,
    amount                         DOUBLE PRECISION,
    created_at                     TIMESTAMP WITHOUT TIME ZONE,
    updated_at                     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment_transactions PRIMARY KEY (id)
);

CREATE TABLE product_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    slug        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_product_categories PRIMARY KEY (id)
);

CREATE TABLE product_variant_details
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_variant_id BIGINT,
    variant_property   VARCHAR(255),
    variant_value      VARCHAR(255),
    CONSTRAINT pk_product_variant_details PRIMARY KEY (id)
);

CREATE TABLE product_variant_medias
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_variant_id BIGINT,
    media_type         VARCHAR(30),
    media_url          VARCHAR(255),
    is_hidden          BOOLEAN,
    uploaded_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product_variant_medias PRIMARY KEY (id)
);

CREATE TABLE product_variants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    BIGINT,
    name          VARCHAR(255),
    image         VARCHAR(255),
    price         DOUBLE PRECISION,
    weight        DOUBLE PRECISION,
    dimensions_mm VARCHAR(255),
    sku           VARCHAR(255),
    stock         DOUBLE PRECISION,
    CONSTRAINT pk_product_variants PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id           BIGINT,
    product_brand         VARCHAR(255),
    total_stock           DOUBLE PRECISION,
    product_name          VARCHAR(255)                            NOT NULL,
    slug                  VARCHAR(255),
    product_profile_image VARCHAR(255),
    description           VARCHAR(255),
    created_at            date,
    updated_at            date,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE promotion_products
(
    promotion_id BIGINT NOT NULL,
    product_id   BIGINT NOT NULL,
    CONSTRAINT pk_promotion_products PRIMARY KEY (promotion_id, product_id)
);

CREATE TABLE promotions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    start_date      TIMESTAMP WITHOUT TIME ZONE,
    end_date        TIMESTAMP WITHOUT TIME ZONE,
    promotion_type  VARCHAR(20),
    promotion_value DOUBLE PRECISION,
    is_valid        BOOLEAN,
    CONSTRAINT pk_promotions PRIMARY KEY (id)
);

CREATE TABLE purchase_order_details
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    purchase_order_id  BIGINT,
    product_variant_id BIGINT,
    vendor_product_id  BIGINT,
    unit               VARCHAR(255),
    vendor_price       DOUBLE PRECISION,
    quantity           INTEGER,
    CONSTRAINT pk_purchase_order_details PRIMARY KEY (id)
);

CREATE TABLE purchase_orders
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vendor_id              BIGINT,
    status                 VARCHAR(255),
    total_price            DOUBLE PRECISION,
    order_date             TIMESTAMP WITHOUT TIME ZONE,
    expected_delivery_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_purchase_orders PRIMARY KEY (id)
);

CREATE TABLE user_addresses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    province         VARCHAR(255),
    district         VARCHAR(255),
    ward             VARCHAR(255),
    specific_address VARCHAR(255),
    CONSTRAINT pk_user_addresses PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fullname                         VARCHAR(255),
    email                            VARCHAR(100)                            NOT NULL,
    password_hash                    VARCHAR(255),
    email_verified                   BOOLEAN                                 NOT NULL,
    activation_token                 VARCHAR(255),
    activation_token_expiration_date TIMESTAMP WITHOUT TIME ZONE,
    reset_token                      VARCHAR(255),
    reset_token_expiration_date      TIMESTAMP WITHOUT TIME ZONE,
    phone_number                     VARCHAR(10),
    image_url                        VARCHAR(255),
    user_role                        VARCHAR(255),
    is_deleted                       BOOLEAN                                 NOT NULL,
    created_at                       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_update                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vendor_price_histories
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vendor_product_id BIGINT,
    price             DOUBLE PRECISION,
    start_date        TIMESTAMP WITHOUT TIME ZONE,
    end_date          TIMESTAMP WITHOUT TIME ZONE,
    notes             VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vendor_price_histories PRIMARY KEY (id)
);

CREATE TABLE vendor_product_properties
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vendor_product_id BIGINT,
    property_name     VARCHAR(255),
    property_value    VARCHAR(255),
    CONSTRAINT pk_vendor_product_properties PRIMARY KEY (id)
);

CREATE TABLE vendor_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vendor_id  BIGINT,
    product_id BIGINT,
    name       VARCHAR(255),
    brand      VARCHAR(255),
    gtin       VARCHAR(255),
    CONSTRAINT pk_vendor_products PRIMARY KEY (id)
);

CREATE TABLE vendor_transactions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    purchase_order_id BIGINT,
    vendor_id         BIGINT,
    payment_method    VARCHAR(255),
    amount            DOUBLE PRECISION,
    transaction_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_vendor_transactions PRIMARY KEY (id)
);

CREATE TABLE vendors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    created_at date,
    updated_at date,
    CONSTRAINT pk_vendors PRIMARY KEY (id)
);

ALTER TABLE customer_orders
    ADD CONSTRAINT uc_customer_orders_address UNIQUE (address_id);

ALTER TABLE payment_transactions
    ADD CONSTRAINT uc_payment_transactions_payment_gateway_transaction UNIQUE (payment_gateway_transaction_id);

ALTER TABLE products
    ADD CONSTRAINT uc_products_slug UNIQUE (slug);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE batches
    ADD CONSTRAINT FK_BATCHES_ON_PO FOREIGN KEY (po_id) REFERENCES purchase_orders (id);

ALTER TABLE batches
    ADD CONSTRAINT FK_BATCHES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE batches
    ADD CONSTRAINT FK_BATCHES_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE customer_carts
    ADD CONSTRAINT FK_CUSTOMER_CARTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE customer_carts
    ADD CONSTRAINT FK_CUSTOMER_CARTS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE customer_orders
    ADD CONSTRAINT FK_CUSTOMER_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES user_addresses (id);

ALTER TABLE customer_orders
    ADD CONSTRAINT FK_CUSTOMER_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE customer_order_details
    ADD CONSTRAINT FK_CUSTOMER_ORDER_DETAILS_ON_CUSTOMER_ORDER FOREIGN KEY (customer_order_id) REFERENCES customer_orders (id);

ALTER TABLE customer_order_details
    ADD CONSTRAINT FK_CUSTOMER_ORDER_DETAILS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT FK_INVENTORY_TRANSACTIONS_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batches (id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT FK_INVENTORY_TRANSACTIONS_ON_CUSTOMER_ORDER FOREIGN KEY (customer_order_id) REFERENCES customer_orders (id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT FK_INVENTORY_TRANSACTIONS_ON_PO FOREIGN KEY (po_id) REFERENCES purchase_orders (id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT FK_INVENTORY_TRANSACTIONS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE payment_transactions
    ADD CONSTRAINT FK_PAYMENT_TRANSACTIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES product_categories (id) ON DELETE SET NULL;

ALTER TABLE product_variants
    ADD CONSTRAINT FK_PRODUCT_VARIANTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_variant_details
    ADD CONSTRAINT FK_PRODUCT_VARIANT_DETAILS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE product_variant_medias
    ADD CONSTRAINT FK_PRODUCT_VARIANT_MEDIAS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE promotion_products
    ADD CONSTRAINT FK_PROMOTION_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE promotion_products
    ADD CONSTRAINT FK_PROMOTION_PRODUCTS_ON_PROMOTION FOREIGN KEY (promotion_id) REFERENCES promotions (id);

ALTER TABLE purchase_orders
    ADD CONSTRAINT FK_PURCHASE_ORDERS_ON_VENDOR FOREIGN KEY (vendor_id) REFERENCES vendors (id);

ALTER TABLE purchase_order_details
    ADD CONSTRAINT FK_PURCHASE_ORDER_DETAILS_ON_PRODUCT_VARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variants (id);

ALTER TABLE purchase_order_details
    ADD CONSTRAINT FK_PURCHASE_ORDER_DETAILS_ON_PURCHASE_ORDER FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id);

ALTER TABLE purchase_order_details
    ADD CONSTRAINT FK_PURCHASE_ORDER_DETAILS_ON_VENDOR_PRODUCT FOREIGN KEY (vendor_product_id) REFERENCES vendor_products (id);

ALTER TABLE user_addresses
    ADD CONSTRAINT FK_USER_ADDRESSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vendor_price_histories
    ADD CONSTRAINT FK_VENDOR_PRICE_HISTORIES_ON_VENDOR_PRODUCT FOREIGN KEY (vendor_product_id) REFERENCES vendor_products (id);

ALTER TABLE vendor_products
    ADD CONSTRAINT FK_VENDOR_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE vendor_products
    ADD CONSTRAINT FK_VENDOR_PRODUCTS_ON_VENDOR FOREIGN KEY (vendor_id) REFERENCES vendors (id);

ALTER TABLE vendor_product_properties
    ADD CONSTRAINT FK_VENDOR_PRODUCT_PROPERTIES_ON_VENDOR_PRODUCT FOREIGN KEY (vendor_product_id) REFERENCES vendor_products (id);

ALTER TABLE vendor_transactions
    ADD CONSTRAINT FK_VENDOR_TRANSACTIONS_ON_PURCHASEORDER FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id);

ALTER TABLE vendor_transactions
    ADD CONSTRAINT FK_VENDOR_TRANSACTIONS_ON_VENDOR FOREIGN KEY (vendor_id) REFERENCES vendors (id);