CREATE TABLE product_properties
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_name  VARCHAR(255),
    property_value VARCHAR(255),
    CONSTRAINT pk_product_properties PRIMARY KEY (id)
);

ALTER TABLE vendor_product_properties
    ADD product_property_id BIGINT;

ALTER TABLE vendor_product_properties
    ADD CONSTRAINT FK_VENDOR_PRODUCT_PROPERTIES_ON_PRODUCT_PROPERTY FOREIGN KEY (product_property_id) REFERENCES product_properties (id);

ALTER TABLE vendor_product_properties
DROP
COLUMN id;

ALTER TABLE vendor_product_properties
DROP
COLUMN property_name;

ALTER TABLE vendor_product_properties
DROP
COLUMN property_value;

ALTER TABLE vendor_product_properties
    ALTER COLUMN vendor_product_id SET NOT NULL;

ALTER TABLE vendor_product_properties
    ADD CONSTRAINT pk_vendor_product_properties PRIMARY KEY (vendor_product_id, product_property_id);