CREATE TABLE variant_details
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variant_name  VARCHAR(255),
    variant_value VARCHAR(255),
    CONSTRAINT pk_variant_details PRIMARY KEY (id)
);

ALTER TABLE product_variant_details
    ADD variant_detail_id BIGINT;

ALTER TABLE product_variant_details
    ADD CONSTRAINT FK_PRODUCT_VARIANT_DETAILS_ON_VARIANT_DETAIL FOREIGN KEY (variant_detail_id) REFERENCES variant_details (id);

ALTER TABLE product_variant_details
DROP
COLUMN id;

ALTER TABLE product_variant_details
DROP
COLUMN variant_property;

ALTER TABLE product_variant_details
DROP
COLUMN variant_value;

ALTER TABLE product_variant_details
    ALTER COLUMN product_variant_id SET NOT NULL;

ALTER TABLE product_variant_details
    ADD CONSTRAINT pk_product_variant_details PRIMARY KEY (product_variant_id, variant_detail_id);