ALTER TABLE product_variant_details
DROP
CONSTRAINT fk_product_variant_details_on_variant_detail;

ALTER TABLE product_variant_details
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE product_variant_details
    ADD variant_name VARCHAR(255);

ALTER TABLE product_variant_details
    ADD variant_value VARCHAR(255);

DROP TABLE variant_details CASCADE;

ALTER TABLE product_variant_details
DROP
COLUMN variant_detail_id;

ALTER TABLE product_variant_details
    ALTER COLUMN product_variant_id DROP NOT NULL;

ALTER TABLE product_variant_details
    ADD CONSTRAINT pk_product_variant_details PRIMARY KEY (id);